### ISSUE TITLE
使用PullHeaderLayout之后，上推至最小高度时滑动异常，用的是api19的小米进行测试

### ISSUE THREAD

**Issue by zer0w0** [race604/FlyRefresh#8]
非常感谢你提供的优秀的源码，经测试，发现了如题目所描述的小问题
public int move(float deltaY) {
        float willTo;
        float consumed = deltaY;
        if (mScroll >= 0) {
            willTo = mScroll + deltaY;
            if (willTo < 0) {
               ...
                }
            } else if (willTo > mMaxHegiht) {  //---------------->改成else if(willTo>mMaxScroll)解决了问题
                consumed -= willTo - mMaxScroll;
                willTo = mMaxScroll;
            }
        } else {
          ...
        }
          ...
    }

**Comment by race604** [comment]
非常感谢，您方便的话，给我发一个 pull request，我 merge 一下
